---
title: "Transit Oriented Development"
author: "Samriddhi Khare"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    code_download: true
    theme: yeti 
    
---

```{r setup, include=FALSE}
  knitr::opts_chunk$set(
    echo = FALSE,
    warning = FALSE,
    message = FALSE,
    out.width = '100%',
    fig.retina =3
  )
```

## R Setup and Installing packages

loading packages and cansus key

```{r setup_packages, warning = FALSE, message = FALSE}
# Load Libraries

library(tidyverse)
library(tidycensus)
library(sf)
library(kableExtra)
library(tidyr)
library(ggplot2)
library(viridis)




options(scipen=999)
options(tigris_class = "sf")

#these are functions developed for this class, so it takes you especially to the book to get those

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette5 <- c("#f0f9e8","#bae4bc","#7bccc4","#43a2ca","#0868ac")

census_api_key('bf2d507651b5a621dbadd44533fb4f3deaab26bf', overwrite = TRUE)

dir.create("output")

```


this is the dataset to use

```{r load_variables, cache=TRUE}

acs_variable_list.2020 <- load_variables(2020, #year
                                         "acs5", #five year ACS estimates
                                         cache = TRUE)

acs_variable_list.2016 <- load_variables(2016, #year
                                         "acs5", #five year ACS estimates
                                         cache = TRUE)
```

B01001B_001E black
B08101_025E people taking public transit to work
B24011_002E people working in business, science, and arts occupations
B25026_001E people living in households
B19013_001 median income
B25058_001E rent
B06012_002E under poverty line
B25097_001 mortgage

### Use `get_acs()` to get 2016 ACS data

Notice this returns "long" data - let's examine it

```{r results='hide'}
tracts16 <-  
  get_acs(geography = "tract",
          variables = c("B25026_001E",#pop
                        "B19013_001E", #med inc
                        "B25058_001E", #rent
                        "B24011_002E" ), #ppl in business science arts 
          year=2016, 
          state = 25,
          county=025, #using the boston/suffolk county FIPS code
          geometry=TRUE) %>% 
  st_transform('ESRI:102728')

```

```{r}
# making it wide from long

tracts16 <- 
  tracts16 %>%
  dplyr::select( -NAME, -moe) %>%
  spread(key = variable, value = estimate) %>% #spread makes it long to wide
  rename(TotalPop = B25026_001, 
         MedInc = B19013_001,
         MedRent = B25058_001, 
         BusArtsScience = B24011_002)

#creating new variable

tracts16 <- 
  tracts16 %>%
  mutate(IncSpentOnRentPCt = ifelse(MedInc > 0, MedRent / MedInc, 0),
         year = "2016") 
```

```{r results='hide'}

#doing the same thing for 2020

tracts20 <- 
  get_acs(geography = "tract", 
          variables = c("B25026_001E",#pop
                        "B19013_001E", #med inc
                        "B25058_001E", #rent
                        "B24011_002E" ), #ppl in business science arts 
          year=2020, 
          state = 25,
          county=025, #using the boston/suffolk county FIPS code
          geometry=TRUE, output="wide")%>%
  st_transform('ESRI:102728') %>%
  rename(TotalPop = B25026_001E, 
         MedInc = B19013_001E,
         MedRent = B25058_001E, 
         BusArtsScience = B24011_002E)%>%
  dplyr::select(-NAME, -ends_with("M")) %>%
  mutate(IncSpentOnRentPCt = ifelse(MedInc > 0, MedRent / MedInc, 0),
         year = "2020")  
```

```{r}
#binding the data
allTracts <- rbind(tracts16,tracts20)
```

```{r}

github_url <-"https://raw.githubusercontent.com/samriddhikhar3/Assignment2/main/data/MBTA_Systemwide_GTFS_Map.geojson"
MBTAStops <- st_read(github_url) %>% 
  st_transform(st_crs(tracts16))  
```

```{r}

clippedMBTA <- 
  st_intersection(MBTAStops, tracts16)

ggplot() + 
  geom_sf(data=st_union(tracts16)) +
  geom_sf(data=clippedMBTA) +
  labs(title="MBTA Stops", 
       subtitle="Boston, MA", 
       caption="Figure 1.1") +
  mapTheme()
```